### ISSUE TITLE
Search doesn't show

### ISSUE THREAD

**Issue by skyteam2019** [spy16/droplets#12]
Hi.
After installing and running the application whenever I search the anything in the query.
http://localhost:8080/search?query=k
This shows "404 page doesn't show"
I am looking at the controller in the .go file and also template .tpl file, but I couldn't find it.
Thanks

**Comment by spy16** [comment]
Sorry, this is not completed yet. 

```golang
// Search finds all the posts matching the parameters in the query.
func (ret *Retriever) Search(ctx context.Context, query Query) ([]domain.Post, error) {
	return nil, errors.New("not implemented")
}
```
