### ISSUE TITLE
ListenAndServe() needs to panic + don't log.Fatal

### ISSUE THREAD

**Issue by sofasurfa** [spy16/droplets#13]
Hi, I'm new to GoLang. But looking at the code, I think that `ListenAndServe()` needs to fatal log that will call `panic` and stop the programme. If `ListenAndServe()` is broken from the get go, take `ListenAndServeTLS(certFile, keyFile)`, if something goes wrong with `certFile` then the program should crash, not return an error that we would only know about when we send an incoming signal (to start graceful shutdown). What do you think?

```
func (gss *Server) ListenAndServe() error {
	go func() {
		gss.server.Addr = gss.Addr
		if err := gss.server.ListenAndServe(); err != http.ErrServerClosed {
			// gss.err = err ---> no need for this
                        log.Fatal(err)  //  logs the error and calls panic
		}
	}()
	return gss.waitForShutdown()
}
```

**Comment by sofasurfa** [comment]
@spy16

**Comment by spy16** [comment]
Made a quick fix for this and pushed. This can probably be simplified a bit. But it's not very complicated either.

**Comment by sofasurfa** [comment]
@spy16 What you've said made a lot of sense. Thanks for your explanation and for pushing the code.
And big thanks for making this useful repository :)
Wishing u all the best!

**Comment by sofasurfa** [comment]
@spy16 Also I noticed that `defer closeSession()` wouldn't execute in the main

```
if err := srv.ListenAndServe(); err != nil {
		lg.Fatalf("http server exited: %s", err)
	}
```
As `Fatalf` logs the error and then calls `os.Exit(1)`. I think it's better to  do this 

```
if err := srv.ListenAndServe(); err != nil {
		lg.Printf("http server exited: %s", err)
}
defer os.Exit(1)
defer closeSession() // this executes first 
```
By calling `defer os.Exit(1)` other defers can also execute before os.Exit.

------ 

Another option would be to use `panic() ` instead of `lg.Fatalf()` in the main, and then after database connection to mongo, we could have this...

```
        db, closeSession, err := mongo.Connect(cfg.MongoURI, true)
	if err != nil {
		panic("failed to connect to mongodb: " + err)
	}

  defer func() {
        if r := recover(); r != nil {
            lg.Printf(r)
            closeSession() 
            os.Exit(1)
        }
    }()

// do the same for server and every where else
if err := srv.ListenAndServe(); err != nil {
		panic("http server exited: " + err)
}
 
```
What do you think?

**Comment by sofasurfa** [comment]
Created a new issue #14
