### ISSUE TITLE
General question about the Dependency Rule

### ISSUE THREAD

**Issue by bj4rtmar** [spy16/droplets#9]
If a layer needs to import from an inner layer, should it only import something from their next inner layer or is it ok to "jump over" inner layers and import from there? For example, is it ok for the interface layer to import from the domain layer (skipping over the usecase layer)?

**Comment by spy16** [comment]
Skipping over is completely fine. The reason for this rule is that a change in an external dependency should have no effect on your core business logic.. since skipping over a layer does not break this promise it should be alright.
